image: Visual Studio 2019

platform:
- x64

install:
  - cmd: node -v
  - cmd: npm -v
  - cmd: npm --loglevel=error i
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote list
build_script:
  - cmd: echo build %build_target%...
  - cmd: build.cmd %build_target% "%x86_64_flags%"
  - cmd: build.cmd %build_target% "%x86_flags%"
  - cmd: node index
  - cmd: dir