image: Visual Studio 2019

platform:
- x64

cache:
  - '%APPDATA%\npm-cache'

install:
  - cmd: choco install gh
  - cmd: echo %_github_token%> .gh_token
  - cmd: refreshenv && gh auth login --with-token < .gh_token
  - cmd: node -v
  - cmd: npm -v
  - cmd: npm --loglevel=error i
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=C:/Python39-x64/Scripts/;%PATH%
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote list
build_script:
  - cmd: echo build %build_target%...
  - cmd: node index
  - cmd: dir
  - cmd: refreshenv && gh release upload %build_target% %build_output_basename%.tgz