#!/usr/bin/env bash

target=$1
version=$2
repo=$3
tag=$4
deps=$5
flags=$6

gh workflow run cmake-linux --field build_target=$target --field build_version=$version --field build_repo=$repo --field build_tag=$tag --field "build_flags=$flags" --field build_deps=$deps --field build_output_basename=$target-$version-arm-linux-gnueabihf --field triple=arm-linux-gnueabihf
gh workflow run cmake-linux --field build_target=$target --field build_version=$version --field build_repo=$repo --field build_tag=$tag --field "build_flags=$flags" --field build_deps=$deps --field build_output_basename=$target-$version-aarch64-linux-gnu --field triple=aarch64-linux-gnu
gh workflow run cmake-linux --field build_target=$target --field build_version=$version --field build_repo=$repo --field build_tag=$tag --field "build_flags=$flags" --field build_deps=$deps --field build_output_basename=$target-$version-x86_64-linux-gnu --field triple=x86_64-linux-gnu
gh workflow run cmake-linux --field build_target=$target --field build_version=$version --field build_repo=$repo --field build_tag=$tag --field "build_flags=$flags" --field build_deps=$deps --field build_output_basename=$target-$version-i386-linux-gnu --field triple=i386-linux-gnu

gh workflow run cmake-macos --field build_target=$target --field build_version=$version --field build_repo=$repo --field build_tag=$tag --field "build_flags=$flags" --field build_deps=$deps --field build_output_basename=$target-$version-x86_64-apple-darwin --field triple=x86_64-apple-darwin
gh workflow run cmake-macos --field build_target=$target --field build_version=$version --field build_repo=$repo --field build_tag=$tag --field "build_flags=$flags" --field build_deps=$deps --field build_output_basename=$target-$version-arm64-apple-darwin --field triple=arm64-apple-darwin

gh workflow run cmake-win --field build_target=$target --field build_version=$version --field build_repo=$repo --field build_tag=$tag --field "build_flags=$flags" --field build_deps=$deps --field build_output_basename=$target-$version-x86_64-pc-windows-msvc-MT --field triple=x86_64-pc-windows-msvc-MT
gh workflow run cmake-win --field build_target=$target --field build_version=$version --field build_repo=$repo --field build_tag=$tag --field "build_flags=$flags" --field build_deps=$deps --field build_output_basename=$target-$version-i386-pc-windows-msvc-MT --field triple=i386-pc-windows-msvc-MT
