#!/usr/bin/env bash

target=$1
version=$2
deps=$3

gh workflow run win --field build_target=$target --field build_version=$version --field "build_flags=-s arch=x86_64 -s compiler.runtime=MT" --field build_output_basename=$target-$version-x86_64-pc-windows-msvc-MT
gh workflow run win --field build_target=$target --field build_version=$version --field "build_flags=-s arch=x86 -s compiler.runtime=MT" --field build_output_basename=$target-$version-i386-pc-windows-msvc-MT
