set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_FLAGS /m32)
set(CMAKE_CXX_FLAGS /m32)
set(CMAKE_MASM_FLAGS /m32)
set(CMAKE_EXE_LINKER_FLAGS /m32)
set(CMAKE_MODULE_LINKER_FLAGS /m32)
set(CMAKE_SHARED_LINKER_FLAGS /m32)
set(CMAKE_STATIC_LINKER_FLAGS /m32)
