set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(CMAKE_C_FLAGS -m32)
set(CMAKE_CXX_FLAGS -m32)
set(CMAKE_ASM_FLAGS -m32)
set(CMAKE_EXE_LINKER_FLAGS -m32)
set(CMAKE_MODULE_LINKER_FLAGS -m32)
set(CMAKE_SHARED_LINKER_FLAGS -m32)
