# This is a basic workflow to help you get started with Actions

name: linux-armv7

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Library Name'     
        required: true
      build_version:
        description: 'Library Version'     
        required: true
      build_flags:
        description: 'Build Flags'     
        required: true
      build_output_basename:
        description: 'Output Basename'     
        required: true

env:
  build_target: ${{ github.event.inputs.build_target }}
  build_version: ${{ github.event.inputs.build_version }}
  build_flags: ${{ github.event.inputs.build_flags }}
  build_output_basename: ${{ github.event.inputs.build_output_basename }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Cross Compiler
        run: |
          sudo apt-get update
          sudo apt-get install libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev build-essential bison flex libssl-dev bc gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
        
      - name: Conan Info
        run: |
          conan user
          conan --version
          conan remote list
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          version: 12.16.0

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm i

      - name: Run a multi-line script
        run: |
          node prepare
          node build
          node sha1sum
          gh release upload $build_target $build_output_basename.tgz --clobber
          gh release upload $build_target $build_output_basename.sha1sum.txt --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
